### PR TITLE
Initial template

### PR DESCRIPTION
**Pull request by hawkz**
Here's a first stab at the homepage responsive layout.

I've put in a quick hack for a test.html butchering the page_en.html to make the test render for now.

### CODE REVIEW

**Comment by ntoll** [comment]
Looking good. Just checking this on the train into London :-)

Noticed a glitch in the footer on smaller view-port devices (but you probably know this already). See attached screenie.

pyedscreenie

**Comment by hawkz** [comment]
You need to try test.html we'll need to use a wrapping div to provide the spacing on the 'normal' template 

~Steve

**Comment by ntoll** [comment]
doh.... too early in the morning!

MUST 
HAVE
COFFEE

:-)

**Comment by ntoll** [comment]
ZOMG that is totally awesome.

There's still an issue with the footer interfering with page width.
predscreenie

**Comment by ntoll** [comment]
This is awesome work Steve, what else remains from a Blanc point of view? Can I have the final (final) versions of the images needed for the rest of the site. Some "blips" I've noticed:

Snakes levitate over paper cut.

pyedsnakes

More levitating snakes:

pyedsnake2

We need updated images for documentation and code

pyedpics

This is *really* exciting.

**Comment by hawkz** [comment]
We haven’t done QA, just wanted to get the structure up so you could work in a context, we’ll now tweak styles to polish off that page, I’ll include the points you’ve raised in that.




-- 


Blanc Limited
Blythe Valley Innovation Centre
Central Boulevard
Solihull, B90 8AJ


+44 (0) 33 33 44 7 800
www.blanc.ltd.uk

**Comment by ntoll** [comment]
Aha... great stuff. I'll merge in content this evening and over the weekend. This is so exciting - I'm doing a happy dance in my chair here in the office and getting funny looks from my more corporate looking colleagues (I usually turn up in shorts and sandals). ;-)

**Comment by hawkz** [comment]
I’ll have another stab this evening. If you could have a quick look at compiling css via wok that might make a big difference for getting other contributors.. we struggled a bit with less on PyConUK, so hopefully this’ll be easier.

So pleased you’re loving it! Hope it’s well received when it goes out :D




-- 


Blanc Limited
Blythe Valley Innovation Centre
Central Boulevard
Solihull, B90 8AJ


+44 (0) 33 33 44 7 800
www.blanc.ltd.uk

**Comment by ntoll** [comment]
Well, you're already name-checked for the world-tour site in the keynote. So desperate to get this in a "good enough" state for Monday to name-check you TWICE.

**Comment by ntoll** [comment]
Great stuff...

Still have levitating Pythons (I notice the Python in this image file doesn't extend to the bottom of the image):

pyedfri1

Also, still need replacement images for the documentation and code sections at the bottom of the page.

pyedfri2

For docs, I guess that means a book - perhaps with an Easter Egg title? "Snake Charming for Beginners", "The Pyckwick Papers", "Pyride and Pyrejudice" etc... ;-)

For code, just use some very simple Python like this:

def hello(name="world!"):
    print("Hello, {}".format(name))

Finally, can you add (or reference) the flag image pack you use so more flags can be added as they are needed..?

Getting there! ;-)

**Pull request merged**
